### ISSUE TITLE
megacli_legacy.rb: cannot load such file -- semver

### ISSUE THREAD

**Issue by sammcj** [jhoblitt/puppet-smartd#62]
I get the following error every run:

```
Error: Facter: error while resolving custom facts in /opt/puppetlabs/puppet/cache/lib/facter/megacli_legacy.rb: cannot load such file -- semver
```

```
# cat /opt/puppetlabs/puppet/cache/lib/facter/megacli_legacy.rb
require 'semver'

# Legacy versions of MegaCLI require different arguments to determine certain
# software and firmware versions.
Facter.add(:megacli_legacy) do
  megacli = Facter.value(:megacli)
  megacli_version = Facter.value(:megacli_version)

  setcode do
    next if megacli.nil?
    next if megacli_version.nil?

    # Modern version assumed from changelog at
    # http://www.lsi.com/downloads/Public/RAID%20Controllers/RAID%20Controllers%20Common%20Files/Linux%20MegaCLI%208.07.10.txt
    actual_version = SemVer.new(megacli_version)
    modern_version = SemVer.new('8.02.16')

    actual_version < modern_version
  end
end
```

We don't use megaraid / megacli anywhere so I'm a little surprised it even tries to load this custom fact actually?

**Comment by dsnt02518** [comment]
I have the same issue on Centos 7.4 with puppet5.
It looks like EPEL's puppet 3.6 provides /usr/share/ruby/vendor_ruby/semver.rb, but since moving to puppet 5 this is no longer provided.
Also puppet 5 uses it's own ruby and gems, so I can work around with:
 ` /opt/puppetlabs/puppet/bin/gem  install semver`
but obviously I'd want puppet to be handling this.
A brief googling seems to indicate that the 'semantic_puppet' gem (which is installed with puppet 5 on CentOS7) is what's required for v5 compatibility maybe?

**Comment by sammcj** [comment]
Yeah I saw the `semantic_puppet` gem as well - I think that'd be the way to go @jhoblitt

**Comment by sammcj** [comment]
oh there was a PR to fix this a year ago: https://github.com/jhoblitt/puppet-smartd/pull/61

@jhoblitt can you merge that PR or use the aformentioned `semantic_puppet` gem?

I also suggest approaching https://voxpupuli.org to see if they'd consider taking over this module so it can be maintained more frequently.

**Comment by apeeters** [comment]
@sammcj The PR was merged last month.
